### ISSUE TITLE
 Showing All Issues The package product 'LanguageServerProtocol' requires minimum platform version 10.15 for the macOS platform, but this target supports 10.13

### ISSUE THREAD

**Issue by weitfly** [ChimeHQ/LanguageServerProtocol#21]
Showing All Issues
The package product 'LanguageServerProtocol' requires minimum platform version 10.15 for the macOS platform, but this target supports 10.13

**Comment by mattmassicotte** [comment]
What is "this target" here? Are you trying to this package with something that needs to support 10.13?

**Comment by weitfly** [comment]
update the latest version look good，thanks

Matt Massicotte ***@***.***> 于2024年8月1日周四 19:44写道：

**Comment by mattmassicotte** [comment]
ok great! sorry for any confusion. There was some churn here a while ago.
